# Импорты

In [40]:
import re
import requests
from collections import Counter
from string import punctuation

import wikipediaapi
import pandas as pd
import spacy
from nltk.corpus import stopwords
from natasha import (
    Segmenter,
    MorphVocab,
    NewsEmbedding,
    NewsMorphTagger,
    NewsNERTagger,
    Doc,
)

# Загрузка текста

In [41]:
with open(r'C:\Users\ivanr\Documents\cod\kursach\texts\genp_text.txt', 'r', encoding='utf-8') as f:
    raw_text = f.read()

# Предобработка

In [42]:
STOPWORDS_RU = set(stopwords.words('russian'))
PUNCT_EXTRA = {'—', '«', '»', "''", '…', '–'}
NOISE = STOPWORDS_RU | set(punctuation) | PUNCT_EXTRA


def clean_raw_text(text: str) -> str:
    parts = []
    for line in text.splitlines():
        line = re.sub(r'^"', '', line)
        line = re.sub(r'"\s*$', ' ', line)
        line = line.replace('—', '-').replace('–', '-')
        line = line.replace('«', '"').replace('»', '"')
        line = re.sub(r'\s+', ' ', line).strip()
        if line:
            parts.append(line)
    return ' '.join(parts)


text = clean_raw_text(raw_text)
print(f'Текст загружен: {len(text)} символов')

Текст загружен: 458221 символов

# Вспомогательные функции

In [43]:
def counter_to_info(counter):
    """Counter → dict {entity: {count: N}}"""
    return {ent: {'count': count} for ent, count in counter.items()}


def merge_raw_stores_max(store1, store2):
    """Объединяет два словаря сущностей, для совпадений берёт максимальный count."""
    merged = {}
    for ent in set(store1) | set(store2):
        info1 = store1.get(ent)
        info2 = store2.get(ent)
        if info1 and info2:
            merged[ent] = {'count': max(info1['count'], info2['count'])}
        else:
            merged[ent] = (info1 or info2).copy()
    return merged

# NER: Natasha

In [44]:
segmenter = Segmenter()
morph_vocab = MorphVocab()
emb = NewsEmbedding()
morph_tagger = NewsMorphTagger(emb)
ner_tagger = NewsNERTagger(emb)

doc_natasha = Doc(text)
doc_natasha.segment(segmenter)
doc_natasha.tag_morph(morph_tagger)
for token in doc_natasha.tokens:
    token.lemmatize(morph_vocab)
doc_natasha.tag_ner(ner_tagger)

persons_natasha = [
    ' '.join(t.lemma for t in span.tokens).lower()
    for span in doc_natasha.spans
    if span.type == 'PER'
]

info_natasha = counter_to_info(Counter(persons_natasha))
print(f'Natasha: {len(persons_natasha)} упоминаний, {len(info_natasha)} уникальных')

Natasha: 1856 упоминаний, 341 уникальных

# NER: spaCy

Если модель ещё не загружена:
```
python -m spacy download ru_core_news_lg
```

In [45]:
nlp = spacy.load('ru_core_news_lg')

doc_spacy = nlp(text)

persons_spacy = [
    ' '.join(t.lemma_ for t in ent).lower()
    for ent in doc_spacy.ents
    if ent.label_ == 'PER'
]

info_spacy = counter_to_info(Counter(persons_spacy))
print(f'spaCy: {len(persons_spacy)} упоминаний, {len(info_spacy)} уникальных')

spaCy: 2045 упоминаний, 358 уникальных

# Объединение результатов

In [46]:
merged_persons = merge_raw_stores_max(info_natasha, info_spacy)
print(f'После объединения: {len(merged_persons)} уникальных сущностей')

После объединения: 534 уникальных сущностей

# Обогащение через Wikipedia

In [ ]:
wiki = wikipediaapi.Wikipedia(
    language='ru',
    user_agent='pelevin-ner-project',
)

PERSON_MARKERS = [
    # биографические глаголы — самый надёжный признак живого человека
    'родился', 'родилась', 'умер', 'умерла', 'скончался', 'скончалась',
    # литература и публицистика
    'писатель', 'писательница', 'поэт', 'поэтесса', 'драматург',
    'переводчик', 'сценарист', 'критик', 'публицист', 'журналист', 'литератор',
    # театр и кино
    'актёр', 'актриса', 'режиссёр',
    # музыка
    'музыкант', 'певец', 'певица', 'композитор',
    # изобразительное искусство
    'художник', 'скульптор', 'архитектор',
    # наука
    'учёный', 'историк', 'философ', 'психолог', 'социолог', 'лингвист',
    # политика и военное дело
    'политик', 'деятель', 'революционер', 'военачальник', 'полководец',
    # предпринимательство и техника
    'предприниматель', 'изобретатель', 'инженер',
    # авиация и космос
    'лётчик', 'космонавт',
    # спорт
    'спортсмен', 'спортсменка',
    # религия и мифология
    'богослов', 'священник', 'монах', 'святой', 'апостол', 'пророк',
    'бог', 'божество',
]

ACTIVITIES = [
    'писатель', 'писательница', 'поэт', 'поэтесса', 'драматург',
    'переводчик', 'сценарист', 'критик', 'публицист', 'журналист', 'литератор',
    'актёр', 'актриса', 'режиссёр',
    'музыкант', 'певец', 'певица', 'композитор',
    'художник', 'скульптор', 'архитектор',
    'учёный', 'историк', 'философ', 'психолог', 'социолог', 'лингвист',
    'политик', 'деятель', 'революционер', 'военачальник', 'полководец',
    'предприниматель', 'изобретатель', 'инженер',
    'лётчик', 'космонавт',
    'спортсмен', 'спортсменка',
    'богослов', 'священник', 'монах', 'святой', 'апостол', 'пророк',
    'бог', 'божество',
]

# признаки страниц-дизамбигуаций и страниц-фамилий
_DISAMBIGUATION_SIGNS = [
    'фамилия',
    'многозначный',
    'неоднозначность',
    'может означать',
    'матронимическ',
    'патронимическ',
]


def is_disambiguation(page) -> bool:
    s = page.summary[:300].lower() if page.summary else ''
    return not s or any(sign in s for sign in _DISAMBIGUATION_SIGNS)


def find_wiki_page(ent: str):
    page = wiki.page(ent.title())
    if page.exists() and not is_disambiguation(page):
        return page

    try:
        r = requests.get(
            'https://ru.wikipedia.org/w/api.php',
            params={
                'action': 'query', 'list': 'search',
                'srsearch': ent, 'format': 'json', 'srlimit': 1,
            },
            timeout=10,
        )
        results = r.json().get('query', {}).get('search', [])
        if results:
            p = wiki.page(results[0]['title'])
            if p.exists():
                return p
    except Exception:
        pass

    return None


final_persons = {}

for ent, info in merged_persons.items():
    page = find_wiki_page(ent)

    if page is None:
        continue

    first_part = page.summary[:600].lower() if page.summary else ''

    if not any(marker in first_part for marker in PERSON_MARKERS):
        continue

    canonical_name = page.title
    entity_activities = [act for act in ACTIVITIES if act in first_part]
    is_deity = 'бог' in entity_activities or 'божество' in entity_activities

    birth_year = death_year = None
    if not is_deity:
        years = re.findall(r'(1[0-9]{3}|20[0-9]{2})', first_part)
        if years:
            birth_year = int(years[0])
        if len(years) >= 2:
            death_year = int(years[1])

    if canonical_name in final_persons:
        final_persons[canonical_name]['count'] += info['count']
    else:
        final_persons[canonical_name] = {
            'count': info['count'],
            'activities': entity_activities,
            'birth_year': birth_year,
            'death_year': death_year,
        }

# Итоговая таблица

In [48]:
df_persons = pd.DataFrame.from_dict(final_persons, orient='index')
df_persons.index.name = 'entity'
df_persons.reset_index(inplace=True)
df_persons

,entity,count,activities,birth_year,death_year
0,Родина,2,[],NaN,NaN
1,Аллах,5,"[пророк, бог, божество]",NaN,NaN
2,"Шиффер, Клаудия",1,[актриса],1970.0,NaN
3,Маркиз де Сад,1,"[писатель, историк, философ, политик]",1740.0,1814.0
4,Будда Шакьямуни,2,[],NaN,NaN
...,...,...,...,...,...
92,"Хаббард, Лафайет Рональд",1,"[писатель, критик]",1911.0,1986.0
93,"Гитлер, Адольф",1,[деятель],1889.0,1945.0
94,"Есенин, Сергей Александрович",1,"[писатель, поэт]",1895.0,1925.0
95,"Исикава, Такубоку",1,"[поэт, критик]",1886.0,1912.0
96,"Битов, Андрей Георгиевич",1,"[писатель, поэт, сценарист, актёр]",1937.0,2018.0

In [49]:
pd.set_option('display.max_rows', None)
df_persons

,entity,count,activities,birth_year,death_year
0,Родина,2,[],NaN,NaN
1,Аллах,5,"[пророк, бог, божество]",NaN,NaN
2,"Шиффер, Клаудия",1,[актриса],1970.0,NaN
3,Маркиз де Сад,1,"[писатель, историк, философ, политик]",1740.0,1814.0
4,Будда Шакьямуни,2,[],NaN,NaN
5,Кулак,1,[режиссёр],NaN,NaN
6,"Тютчев, Фёдор Иванович",2,"[поэт, переводчик, публицист]",1803.0,1873.0
7,"Троцкий, Лев Давидович",2,"[деятель, революционер]",1879.0,1940.0
8,"Березовский, Борис",1,"[политик, предприниматель]",1946.0,2013.0
9,"Кинг, Стивен",1,[писатель],1947.0,NaN
10,"Ленин, Владимир Ильич",5,"[политик, деятель, революционер]",1870.0,1924.0
11,Лик,1,[бог],NaN,NaN
12,"Захер-Мазох, Леопольд фон",1,[писатель],1836.0,1895.0
13,Фредди Меркьюри,1,"[певец, композитор]",1946.0,1991.0
14,"Геббельс, Йозеф",1,[политик],1897.0,1945.0
15,Бэтмен,2,[художник],1939.0,2015.0
16,"Рейган, Рональд",1,"[актёр, политик, деятель]",1911.0,2004.0
17,"Ариосто, Лудовико",1,"[поэт, драматург]",1474.0,1533.0
18,"Чубайс, Анатолий Борисович",3,[деятель],1955.0,1991.0
19,"Зайцев, Вячеслав Михайлович",1,[художник],1938.0,2023.0
20,Стол,1,[деятель],NaN,NaN
21,Маразм,1,[деятель],NaN,NaN
22,Мансур аль-Халладж,1,"[богослов, бог]",NaN,NaN
23,"Пикассо, Пабло",3,"[художник, скульптор]",1881.0,1973.0
24,Буратино,1,[актёр],1936.0,1881.0
25,"Аксёнов, Василий Павлович",2,"[писатель, драматург, переводчик, сценарист, ж...",1932.0,2009.0
26,"Че Гевара, Эрнесто",4,"[деятель, революционер]",1928.0,1967.0
27,Семён,8,[бог],NaN,NaN
28,"Пушкин, Александр Сергеевич",2,"[поэт, драматург, критик, публицист, журналист...",1799.0,1837.0
29,"Ницше, Фридрих",1,"[критик, композитор, художник, философ]",1844.0,1900.0
30,Фон,1,[психолог],NaN,NaN
31,Harley-Davidson,3,[политик],1982.0,NaN
32,"Бунюэль, Луис",1,"[сценарист, режиссёр]",1900.0,1983.0
33,Мышление,1,"[философ, деятель]",NaN,NaN
34,"Шекспир, Уильям",2,"[поэт, драматург]",1564.0,1616.0
35,"Эйнштейн, Альберт",1,[деятель],1879.0,1955.0
36,"Гойя, Франсиско",1,[художник],1746.0,1828.0
37,Сирруш,9,[бог],NaN,NaN
38,"Далёкий, Николай Александрович",1,"[писатель, сценарист]",1909.0,1976.0
39,Малюта Скуратов,29,[деятель],1573.0,1570.0
40,"Радуев, Салман Бетырович",32,[военачальник],1967.0,2002.0
41,"Чехов, Антон Павлович",3,"[писатель, драматург, публицист, деятель]",1860.0,1904.0
42,Свобода,1,[философ],NaN,NaN
43,Иштар,10,"[бог, божество]",NaN,NaN
44,Ха,1,[бог],NaN,NaN
45,Лень,1,"[психолог, деятель]",NaN,NaN
46,Аттила,2,[историк],NaN,NaN
47,Шахтёрский,1,[бог],NaN,NaN
48,Салман,6,"[учёный, пророк]",1935.0,1969.0
49,"Сервантес, Мигель де",1,"[писатель, поэт, драматург]",1547.0,1616.0
50,"Оруэлл, Джордж",1,"[писатель, критик, публицист, журналист]",1903.0,1950.0
51,Серёга,2,[],1976.0,2004.0
52,"Гагарин, Юрий Алексеевич",3,"[лётчик, космонавт]",1934.0,1968.0
53,"Брежнев, Леонид Ильич",1,[деятель],1906.0,1906.0
54,"Райс, Эл",1,[писатель],1926.0,2022.0
55,Малютины,1,[предприниматель],NaN,NaN
56,Веспасиан,1,[политик],NaN,NaN
57,"Олдмен, Гэри",1,"[критик, актёр, режиссёр, музыкант]",1958.0,1990.0
58,"Бандерас, Антонио",4,"[актёр, режиссёр]",1960.0,NaN
59,Энки,8,"[бог, божество]",NaN,NaN
60,"Пастернак, Борис Леонидович",1,"[поэт, переводчик]",1890.0,1960.0
61,Энкиду,15,[бог],NaN,NaN
62,Дума,1,[поэт],1838.0,NaN
63,Адам,1,[бог],NaN,NaN
64,Серёжа,16,[режиссёр],1955.0,1960.0
65,"Грибоедов, Александр Сергеевич",1,"[писатель, драматург, композитор, историк, лин...",1795.0,1829.0
66,"Ростропович, Мстислав Леопольдович",4,"[композитор, деятель]",1927.0,2007.0
67,"Веласкес, Диего",1,[художник],1599.0,1660.0
68,Иезекииль,1,"[деятель, пророк, бог]",NaN,NaN
69,"Ханин, Зеэв",1,[учёный],1959.0,NaN
70,"Чаадаев, Пётр Яковлевич",2,"[публицист, философ]",1794.0,1856.0
71,Василий Блаженный,1,[святой],1462.0,1468.0
72,"Бандера, Степан Андреевич",1,"[деятель, священник]",1909.0,1959.0
73,Мата Хари,1,[деятель],1876.0,1876.0
74,Ариэль,2,[пророк],NaN,NaN
75,Кибела,1,[бог],NaN,NaN
76,"Пирсиг, Роберт",1,"[писатель, философ]",1928.0,2017.0
77,"Доулу, Кенан",1,[певец],1974.0,NaN
78,"Черномырдин, Виктор Степанович",1,[деятель],1938.0,2010.0
79,Аминь,1,[бог],NaN,NaN
80,Дождь,1,[поэт],NaN,NaN
81,Вавилон,5,[бог],NaN,NaN
82,"Ельцин, Борис Николаевич",12,[деятель],1931.0,2007.0
83,"Маяковский, Владимир Владимирович",1,"[поэт, драматург, сценарист, актёр, режиссёр, ...",1893.0,1930.0
84,Мардук,3,"[бог, божество]",NaN,NaN
85,"Уорхол, Энди",1,"[писатель, режиссёр, художник]",1928.0,1987.0
86,Баал,1,"[бог, божество]",NaN,NaN
87,"Де Вито, Дэнни",1,"[актёр, режиссёр]",1944.0,NaN
88,Ошо,1,[бог],NaN,NaN
89,Kenzo (бренд),2,[],1970.0,1964.0
90,"Достоевский, Фёдор Михайлович",3,"[писатель, публицист, философ, психолог]",1821.0,1881.0
91,Гамлет,3,[драматург],1599.0,1601.0
92,"Хаббард, Лафайет Рональд",1,"[писатель, критик]",1911.0,1986.0
93,"Гитлер, Адольф",1,[деятель],1889.0,1945.0
94,"Есенин, Сергей Александрович",1,"[писатель, поэт]",1895.0,1925.0
95,"Исикава, Такубоку",1,"[поэт, критик]",1886.0,1912.0
96,"Битов, Андрей Георгиевич",1,"[писатель, поэт, сценарист, актёр]",1937.0,2018.0